from pydantic_ai import Agent, RunContext
from pydantic_ai.models.ollama import OllamaModel
from pydantic_ai.providers.ollama import OllamaProvider
from pydantic_ai.output import NativeOutput
from models.npc_concept import NPCConceptList
from models.quest import Quest
from tools.npc_tools import get_ancestries_with_descriptions, get_classes_with_descriptions
from tools.name_tools import get_npc_name

def get_npcs_creation_agent():
    model = OllamaModel(
        'gemma-quest',
        provider = OllamaProvider(base_url='http://localhost:11434/v1')
    )

    npcs_agent = Agent(
        model,
        deps_type = Quest,
        system_prompt = (
            "You are a creative writer and a Pathfinder 2e Game Master. "
            "Your job is to create a list of NPC concepts for a provided quest for the purposes of creating an adventure module. "
            "You will be provided a quest summary, act summaries and scene summaries in each act. "
            "Scene summaries also include the type of encounter (either social, combat, skill challenge or hazard) that appears in the sence. "
            "An npc concept includes the npc's ancestry (selected from a list of ancestries provided by the get_ancestries_with_descriptions tool), "
            "the name of the npc (generated from the get_npc_name tool by providing the selected ancestry), "
            "the class of the npc (generated from the get_classes_with_descriptions tool), "
            "the a description of the role the npc plays in the quest, "
            "and a short description of the role the npc plays in each scene the npc appears in. "
            "Each scene role description should begin with the act number and scene number, for example: \n"
            "'Act One, Scene One: ...'\n"
            "'Act One, Scene Two: ...'\n"
            "'Act Two, Scene Four: ...'\n"
            "'Act Three, Scene Six: ...'\n"
            "NPCs do not need to appear in every scene, and should only be included in scenes where the npc plays a role to further the narrative of the quest based on the scene summary. "
            "All scenes that include a social encounter should include at least one npc. "
            "Scenes with combat, skill challenge or hazard encounters might not include any NPCs depending on the purposes of the narrative. "
            "When creating an NPC you will need to call the tools in the following order:\n"
            "1. Select an ancestry from the ancestries with descriptions using the get_ancestries_with_descriptions tool.\n"
            "2. Generate a name for the npc using the get_npc_name tool by providing the selected ancestry.\n"
            "3. Select a class for the npc from the list generated by the get_classes_with_descriptions tool.\n"
            "4. Generate a description of the role the npc plays in the quest.\n"
            "5. For each scene the npc appears in, generate a description of the role the npc plays in the scene\n"
            "Do not include any information other than the list of NPC concepts. "
        )
    )

    # Register our tools
    npcs_agent.tool_plain(get_ancestries_with_descriptions)
    npcs_agent.tool(get_npc_name)
    npcs_agent.tool_plain(get_classes_with_descriptions)
    
    return npcs_agent

def get_npcs_extraction_agent():
    model = OllamaModel(
        'qwen2.5-quest',
        provider = OllamaProvider(base_url='http://localhost:11434/v1')
    )

    npcs_agent = Agent(
        model,
        output_type = NativeOutput(NPCConceptList),
        system_prompt = (
            "You are an expert Data Extraction Agent. "
            "Your only purpose is to extract the NPC concept data from the provided list of NPC concepts. "
            "Each NPC concept (NPCConcept) includes the npc's name, ancestry, class, quest role, and a list of scene roles (List[NPCSceneRoles]). "
            "Each scene role includes the act number, scene number and the role the npc plays in the scene."
            "Do not add any additional information or simplify/summarize any part of the NPC concepts, just extract the data and return it."
        )
    )
    
    return npcs_agent